[package]
name = "kala"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
ring = "0.17.14"
flatbuffers = "25.2.10"
tokio = {version =  "1.45.1", features = ["full"]}
rocksdb = {version = "0.23", default-features = false, features = ["lz4"]}
bincode = "*"
anyhow = "*"
vdf-streamer = {path = "../vdf" }